"""sprint4 trading sleep decisions

Revision ID: 436dfab1ec67
Revises: 67941129bd1c
Create Date: 2026-04-06 12:36:09.854229
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers
revision: str = "436dfab1ec67"
down_revision: str | None = "67941129bd1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_templates",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("decision_type", sa.String(length=50), nullable=False),
        sa.Column("default_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_templates")),
        schema="decisions",
    )
    op.create_table(
        "decisions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decision_type", sa.String(length=50), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_analysis", sa.Text(), nullable=True),
        sa.Column("ai_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("chosen_option", sa.String(length=200), nullable=True),
        sa.Column("chosen_at", sa.DateTime(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("outcome_rating", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_decisions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        schema="decisions",
    )
    op.create_index(
        op.f("ix_decisions_decisions_user_id"),
        "decisions",
        ["user_id"],
        unique=False,
        schema="decisions",
    )
    op.create_table(
        "sleep_debts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("calculated_date", sa.Date(), nullable=False),
        sa.Column("optimal_hours", sa.Float(), nullable=False),
        sa.Column("actual_hours_7d_avg", sa.Float(), nullable=False),
        sa.Column("debt_hours", sa.Float(), nullable=False),
        sa.Column("trend", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_sleep_debts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sleep_debts")),
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_debts_calculated_date"),
        "sleep_debts",
        ["calculated_date"],
        unique=False,
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_debts_user_id"),
        "sleep_debts",
        ["user_id"],
        unique=False,
        schema="sleep",
    )
    op.create_table(
        "sleep_recommendations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recommendation_date", sa.Date(), nullable=False),
        sa.Column("recommended_bedtime", sa.String(length=5), nullable=False),
        sa.Column("recommended_wake_time", sa.String(length=5), nullable=False),
        sa.Column("recommended_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("followed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_sleep_recommendations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sleep_recommendations")),
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_recommendations_recommendation_date"),
        "sleep_recommendations",
        ["recommendation_date"],
        unique=False,
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_recommendations_user_id"),
        "sleep_recommendations",
        ["user_id"],
        unique=False,
        schema="sleep",
    )
    op.create_table(
        "sleep_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("sleep_date", sa.Date(), nullable=False),
        sa.Column("bedtime", sa.DateTime(), nullable=False),
        sa.Column("wake_time", sa.DateTime(), nullable=False),
        sa.Column("sleep_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("time_to_fall_asleep_minutes", sa.Integer(), nullable=True),
        sa.Column("interruptions", sa.Integer(), nullable=False),
        sa.Column("sleep_quality", sa.Float(), nullable=False),
        sa.Column("deep_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("light_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_sleep_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sleep_records")),
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_records_sleep_date"),
        "sleep_records",
        ["sleep_date"],
        unique=False,
        schema="sleep",
    )
    op.create_index(
        op.f("ix_sleep_sleep_records_user_id"),
        "sleep_records",
        ["user_id"],
        unique=False,
        schema="sleep",
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_invested", sa.Float(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("total_pnl", sa.Float(), nullable=False),
        sa.Column("daily_pnl", sa.Float(), nullable=False),
        sa.Column("holdings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_portfolio_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_portfolio_snapshots_snapshot_date"),
        "portfolio_snapshots",
        ["snapshot_date"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_portfolio_snapshots_user_id"),
        "portfolio_snapshots",
        ["user_id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "trade_logs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.Column("fees", sa.Float(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("trade_time", sa.Time(), nullable=True),
        sa.Column("strategy", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_trade_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_logs")),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_trade_logs_symbol"),
        "trade_logs",
        ["symbol"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_trade_logs_trade_date"),
        "trade_logs",
        ["trade_date"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_trade_logs_user_id"),
        "trade_logs",
        ["user_id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "watchlist",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("alert_price_above", sa.Float(), nullable=True),
        sa.Column("alert_price_below", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_watchlist_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_watchlist_user_id"),
        "watchlist",
        ["user_id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "price_alerts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=10), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=True),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_price_alerts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["trading.watchlist.id"],
            name=op.f("fk_price_alerts_watchlist_id_watchlist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_alerts")),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_price_alerts_user_id"),
        "price_alerts",
        ["user_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_price_alerts_watchlist_id"),
        "price_alerts",
        ["watchlist_id"],
        unique=False,
        schema="trading",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_trading_price_alerts_watchlist_id"), table_name="price_alerts", schema="trading"
    )
    op.drop_index(
        op.f("ix_trading_price_alerts_user_id"), table_name="price_alerts", schema="trading"
    )
    op.drop_table("price_alerts", schema="trading")
    op.drop_index(op.f("ix_trading_watchlist_user_id"), table_name="watchlist", schema="trading")
    op.drop_table("watchlist", schema="trading")
    op.drop_index(op.f("ix_trading_trade_logs_user_id"), table_name="trade_logs", schema="trading")
    op.drop_index(
        op.f("ix_trading_trade_logs_trade_date"), table_name="trade_logs", schema="trading"
    )
    op.drop_index(op.f("ix_trading_trade_logs_symbol"), table_name="trade_logs", schema="trading")
    op.drop_table("trade_logs", schema="trading")
    op.drop_index(
        op.f("ix_trading_portfolio_snapshots_user_id"),
        table_name="portfolio_snapshots",
        schema="trading",
    )
    op.drop_index(
        op.f("ix_trading_portfolio_snapshots_snapshot_date"),
        table_name="portfolio_snapshots",
        schema="trading",
    )
    op.drop_table("portfolio_snapshots", schema="trading")
    op.drop_index(
        op.f("ix_sleep_sleep_records_user_id"), table_name="sleep_records", schema="sleep"
    )
    op.drop_index(
        op.f("ix_sleep_sleep_records_sleep_date"), table_name="sleep_records", schema="sleep"
    )
    op.drop_table("sleep_records", schema="sleep")
    op.drop_index(
        op.f("ix_sleep_sleep_recommendations_user_id"),
        table_name="sleep_recommendations",
        schema="sleep",
    )
    op.drop_index(
        op.f("ix_sleep_sleep_recommendations_recommendation_date"),
        table_name="sleep_recommendations",
        schema="sleep",
    )
    op.drop_table("sleep_recommendations", schema="sleep")
    op.drop_index(op.f("ix_sleep_sleep_debts_user_id"), table_name="sleep_debts", schema="sleep")
    op.drop_index(
        op.f("ix_sleep_sleep_debts_calculated_date"), table_name="sleep_debts", schema="sleep"
    )
    op.drop_table("sleep_debts", schema="sleep")
    op.drop_index(
        op.f("ix_decisions_decisions_user_id"), table_name="decisions", schema="decisions"
    )
    op.drop_table("decisions", schema="decisions")
    op.drop_table("decision_templates", schema="decisions")
    # ### end Alembic commands ###
