"""sprint3 messaging voice study fitness

Revision ID: 67941129bd1c
Revises: f439e40f9fce
Create Date: 2026-04-06 12:08:33.424121
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '67941129bd1c'
down_revision: Union[str, None] = 'f439e40f9fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_forecasts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('hourly_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('peak_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('low_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_energy_forecasts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_forecasts')),
    schema='fitness'
    )
    op.create_index(op.f('ix_fitness_energy_forecasts_forecast_date'), 'energy_forecasts', ['forecast_date'], unique=False, schema='fitness')
    op.create_index(op.f('ix_fitness_energy_forecasts_user_id'), 'energy_forecasts', ['user_id'], unique=False, schema='fitness')
    op.create_table('fitness_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_fitness_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_devices')),
    sa.UniqueConstraint('device_id', name=op.f('uq_fitness_devices_device_id')),
    schema='fitness'
    )
    op.create_index(op.f('ix_fitness_fitness_devices_user_id'), 'fitness_devices', ['user_id'], unique=False, schema='fitness')
    op.create_table('workout_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('heart_rate_avg', sa.Float(), nullable=True),
    sa.Column('heart_rate_max', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_workout_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs')),
    schema='fitness'
    )
    op.create_index(op.f('ix_fitness_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False, schema='fitness')
    op.create_index(op.f('ix_fitness_workout_logs_workout_date'), 'workout_logs', ['workout_date'], unique=False, schema='fitness')
    op.create_table('notification_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_notification_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs')),
    schema='messaging'
    )
    op.create_index(op.f('ix_messaging_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False, schema='messaging')
    op.create_table('telegram_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_telegram_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_users')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_telegram_users_telegram_chat_id')),
    schema='messaging'
    )
    op.create_index(op.f('ix_messaging_telegram_users_user_id'), 'telegram_users', ['user_id'], unique=True, schema='messaging')
    op.create_table('subjects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('syllabus_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_subjects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    schema='study'
    )
    op.create_index(op.f('ix_study_subjects_user_id'), 'subjects', ['user_id'], unique=False, schema='study')
    op.create_table('voice_commands',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('audio_hash', sa.String(length=64), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_voice_commands_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_commands')),
    schema='voice'
    )
    op.create_index(op.f('ix_voice_voice_commands_user_id'), 'voice_commands', ['user_id'], unique=False, schema='voice')
    op.create_table('health_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source_device_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_device_id'], ['fitness.fitness_devices.id'], name=op.f('fk_health_metrics_source_device_id_fitness_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_health_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_metrics')),
    schema='fitness'
    )
    op.create_index(op.f('ix_fitness_health_metrics_metric_type'), 'health_metrics', ['metric_type'], unique=False, schema='fitness')
    op.create_index(op.f('ix_fitness_health_metrics_recorded_at'), 'health_metrics', ['recorded_at'], unique=False, schema='fitness')
    op.create_index(op.f('ix_fitness_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False, schema='fitness')
    op.create_table('mock_tests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['study.subjects.id'], name=op.f('fk_mock_tests_subject_id_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_mock_tests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_tests')),
    schema='study'
    )
    op.create_index(op.f('ix_study_mock_tests_date'), 'mock_tests', ['date'], unique=False, schema='study')
    op.create_index(op.f('ix_study_mock_tests_subject_id'), 'mock_tests', ['subject_id'], unique=False, schema='study')
    op.create_index(op.f('ix_study_mock_tests_user_id'), 'mock_tests', ['user_id'], unique=False, schema='study')
    op.create_table('revision_cards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['study.subjects.id'], name=op.f('fk_revision_cards_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_revision_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_cards')),
    schema='study'
    )
    op.create_index(op.f('ix_study_revision_cards_next_review_date'), 'revision_cards', ['next_review_date'], unique=False, schema='study')
    op.create_index(op.f('ix_study_revision_cards_subject_id'), 'revision_cards', ['subject_id'], unique=False, schema='study')
    op.create_index(op.f('ix_study_revision_cards_user_id'), 'revision_cards', ['user_id'], unique=False, schema='study')
    op.create_table('study_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topics_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comprehension_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['study.subjects.id'], name=op.f('fk_study_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions')),
    schema='study'
    )
    op.create_index(op.f('ix_study_study_sessions_session_date'), 'study_sessions', ['session_date'], unique=False, schema='study')
    op.create_index(op.f('ix_study_study_sessions_subject_id'), 'study_sessions', ['subject_id'], unique=False, schema='study')
    op.create_index(op.f('ix_study_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False, schema='study')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_study_sessions_user_id'), table_name='study_sessions', schema='study')
    op.drop_index(op.f('ix_study_study_sessions_subject_id'), table_name='study_sessions', schema='study')
    op.drop_index(op.f('ix_study_study_sessions_session_date'), table_name='study_sessions', schema='study')
    op.drop_table('study_sessions', schema='study')
    op.drop_index(op.f('ix_study_revision_cards_user_id'), table_name='revision_cards', schema='study')
    op.drop_index(op.f('ix_study_revision_cards_subject_id'), table_name='revision_cards', schema='study')
    op.drop_index(op.f('ix_study_revision_cards_next_review_date'), table_name='revision_cards', schema='study')
    op.drop_table('revision_cards', schema='study')
    op.drop_index(op.f('ix_study_mock_tests_user_id'), table_name='mock_tests', schema='study')
    op.drop_index(op.f('ix_study_mock_tests_subject_id'), table_name='mock_tests', schema='study')
    op.drop_index(op.f('ix_study_mock_tests_date'), table_name='mock_tests', schema='study')
    op.drop_table('mock_tests', schema='study')
    op.drop_index(op.f('ix_fitness_health_metrics_user_id'), table_name='health_metrics', schema='fitness')
    op.drop_index(op.f('ix_fitness_health_metrics_recorded_at'), table_name='health_metrics', schema='fitness')
    op.drop_index(op.f('ix_fitness_health_metrics_metric_type'), table_name='health_metrics', schema='fitness')
    op.drop_table('health_metrics', schema='fitness')
    op.drop_index(op.f('ix_voice_voice_commands_user_id'), table_name='voice_commands', schema='voice')
    op.drop_table('voice_commands', schema='voice')
    op.drop_index(op.f('ix_study_subjects_user_id'), table_name='subjects', schema='study')
    op.drop_table('subjects', schema='study')
    op.drop_index(op.f('ix_messaging_telegram_users_user_id'), table_name='telegram_users', schema='messaging')
    op.drop_table('telegram_users', schema='messaging')
    op.drop_index(op.f('ix_messaging_notification_logs_user_id'), table_name='notification_logs', schema='messaging')
    op.drop_table('notification_logs', schema='messaging')
    op.drop_index(op.f('ix_fitness_workout_logs_workout_date'), table_name='workout_logs', schema='fitness')
    op.drop_index(op.f('ix_fitness_workout_logs_user_id'), table_name='workout_logs', schema='fitness')
    op.drop_table('workout_logs', schema='fitness')
    op.drop_index(op.f('ix_fitness_fitness_devices_user_id'), table_name='fitness_devices', schema='fitness')
    op.drop_table('fitness_devices', schema='fitness')
    op.drop_index(op.f('ix_fitness_energy_forecasts_user_id'), table_name='energy_forecasts', schema='fitness')
    op.drop_index(op.f('ix_fitness_energy_forecasts_forecast_date'), table_name='energy_forecasts', schema='fitness')
    op.drop_table('energy_forecasts', schema='fitness')
    # ### end Alembic commands ###
