"""initial schema all modules

Revision ID: f439e40f9fce
Revises: 
Create Date: 2026-04-06 11:27:34.648951
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'f439e40f9fce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('USER_REGISTER', 'USER_LOGIN', 'USER_LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_CHANGE', 'SCHEDULE_GENERATE', 'SCHEDULE_RESCHEDULE', 'BLOCK_CREATE', 'BLOCK_UPDATE', 'BLOCK_COMPLETE', 'HABIT_CREATE', 'HABIT_CHECK_IN', 'JOURNAL_CREATE', 'JOURNAL_READ', 'MEDICINE_TAKEN', 'MEDICINE_MISSED', 'AI_CALL', 'DATA_EXPORT', 'DATA_DELETE', 'SETTINGS_CHANGE', name='auditaction', schema='audit'), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='audit')
    op.create_table('families',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families')),
    schema='auth'
    )
    op.create_table('refresh_token_blacklist',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token_blacklist')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_token_blacklist_jti'), 'refresh_token_blacklist', ['jti'], unique=True, schema='auth')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'FAMILY', 'GUEST', name='userrole', schema='auth'), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('wake_time', sa.String(length=5), nullable=False),
    sa.Column('sleep_time', sa.String(length=5), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('journal_passphrase_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['auth.families.id'], name=op.f('fk_users_family_id_families')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices')),
    sa.UniqueConstraint('device_fingerprint', name=op.f('uq_user_devices_device_fingerprint')),
    schema='auth'
    )
    op.create_table('email_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('oauth_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_email_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_accounts')),
    schema='email_intel'
    )
    op.create_index(op.f('ix_email_intel_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False, schema='email_intel')
    op.create_table('email_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('priority_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_email_summaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_summaries')),
    schema='email_intel'
    )
    op.create_index(op.f('ix_email_intel_email_summaries_summary_date'), 'email_summaries', ['summary_date'], unique=False, schema='email_intel')
    op.create_index(op.f('ix_email_intel_email_summaries_user_id'), 'email_summaries', ['user_id'], unique=False, schema='email_intel')
    op.create_table('habits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKDAYS', 'WEEKENDS', 'CUSTOM', name='habitfrequency', schema='habits'), nullable=False),
    sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('auto_schedule', sa.Boolean(), nullable=False),
    sa.Column('schedule_category', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits')),
    schema='habits'
    )
    op.create_index(op.f('ix_habits_habits_user_id'), 'habits', ['user_id'], unique=False, schema='habits')
    op.create_table('procrastination_signals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('missed_habits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missed_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_procrastination_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procrastination_signals')),
    schema='habits'
    )
    op.create_index(op.f('ix_habits_procrastination_signals_user_id'), 'procrastination_signals', ['user_id'], unique=False, schema='habits')
    op.create_table('journal_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=False),
    sa.Column('mood', sa.Enum('GREAT', 'GOOD', 'OKAY', 'LOW', 'BAD', name='journalmood', schema='journal'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('encrypted_summary', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_journal_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries')),
    schema='journal'
    )
    op.create_index(op.f('ix_journal_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False, schema='journal')
    op.create_index(op.f('ix_journal_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False, schema='journal')
    op.create_table('medicines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('medicine_type', sa.Enum('PRESCRIPTION', 'SUPPLEMENT', 'VITAMIN', 'OTHER', name='medicinetype', schema='medicine'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('reminder_times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('with_food', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refill_reminder_days', sa.Integer(), nullable=False),
    sa.Column('remaining_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_medicines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines')),
    schema='medicine'
    )
    op.create_index(op.f('ix_medicine_medicines_user_id'), 'medicines', ['user_id'], unique=False, schema='medicine')
    op.create_table('daily_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='planstatus', schema='scheduler'), nullable=False),
    sa.Column('generation_model', sa.String(length=50), nullable=False),
    sa.Column('generation_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_score', sa.Float(), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_daily_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plans')),
    schema='scheduler'
    )
    op.create_index(op.f('ix_scheduler_daily_plans_plan_date'), 'daily_plans', ['plan_date'], unique=False, schema='scheduler')
    op.create_index(op.f('ix_scheduler_daily_plans_user_id'), 'daily_plans', ['user_id'], unique=False, schema='scheduler')
    op.create_table('habit_check_ins',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.habits.id'], name=op.f('fk_habit_check_ins_habit_id_habits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_check_ins')),
    schema='habits'
    )
    op.create_index(op.f('ix_habits_habit_check_ins_check_date'), 'habit_check_ins', ['check_date'], unique=False, schema='habits')
    op.create_index(op.f('ix_habits_habit_check_ins_habit_id'), 'habit_check_ins', ['habit_id'], unique=False, schema='habits')
    op.create_table('medicine_logs',
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('taken_at', sa.Time(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.medicines.id'], name=op.f('fk_medicine_logs_medicine_id_medicines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_logs')),
    schema='medicine'
    )
    op.create_index(op.f('ix_medicine_medicine_logs_log_date'), 'medicine_logs', ['log_date'], unique=False, schema='medicine')
    op.create_index(op.f('ix_medicine_medicine_logs_medicine_id'), 'medicine_logs', ['medicine_id'], unique=False, schema='medicine')
    op.create_table('reschedule_events',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['scheduler.daily_plans.id'], name=op.f('fk_reschedule_events_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reschedule_events')),
    schema='scheduler'
    )
    op.create_table('schedule_blocks',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('WORK', 'STUDY', 'FITNESS', 'MEAL', 'SLEEP', 'PERSONAL', 'SOCIAL', 'HEALTH', 'COMMUTE', 'BREAK', 'ROUTINE', 'BUFFER', name='blockcategory', schema='scheduler'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'RESCHEDULED', name='blockstatus', schema='scheduler'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_module', sa.String(length=50), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['scheduler.daily_plans.id'], name=op.f('fk_schedule_blocks_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_blocks')),
    schema='scheduler'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_blocks', schema='scheduler')
    op.drop_table('reschedule_events', schema='scheduler')
    op.drop_index(op.f('ix_medicine_medicine_logs_medicine_id'), table_name='medicine_logs', schema='medicine')
    op.drop_index(op.f('ix_medicine_medicine_logs_log_date'), table_name='medicine_logs', schema='medicine')
    op.drop_table('medicine_logs', schema='medicine')
    op.drop_index(op.f('ix_habits_habit_check_ins_habit_id'), table_name='habit_check_ins', schema='habits')
    op.drop_index(op.f('ix_habits_habit_check_ins_check_date'), table_name='habit_check_ins', schema='habits')
    op.drop_table('habit_check_ins', schema='habits')
    op.drop_index(op.f('ix_scheduler_daily_plans_user_id'), table_name='daily_plans', schema='scheduler')
    op.drop_index(op.f('ix_scheduler_daily_plans_plan_date'), table_name='daily_plans', schema='scheduler')
    op.drop_table('daily_plans', schema='scheduler')
    op.drop_index(op.f('ix_medicine_medicines_user_id'), table_name='medicines', schema='medicine')
    op.drop_table('medicines', schema='medicine')
    op.drop_index(op.f('ix_journal_journal_entries_user_id'), table_name='journal_entries', schema='journal')
    op.drop_index(op.f('ix_journal_journal_entries_entry_date'), table_name='journal_entries', schema='journal')
    op.drop_table('journal_entries', schema='journal')
    op.drop_index(op.f('ix_habits_procrastination_signals_user_id'), table_name='procrastination_signals', schema='habits')
    op.drop_table('procrastination_signals', schema='habits')
    op.drop_index(op.f('ix_habits_habits_user_id'), table_name='habits', schema='habits')
    op.drop_table('habits', schema='habits')
    op.drop_index(op.f('ix_email_intel_email_summaries_user_id'), table_name='email_summaries', schema='email_intel')
    op.drop_index(op.f('ix_email_intel_email_summaries_summary_date'), table_name='email_summaries', schema='email_intel')
    op.drop_table('email_summaries', schema='email_intel')
    op.drop_index(op.f('ix_email_intel_email_accounts_user_id'), table_name='email_accounts', schema='email_intel')
    op.drop_table('email_accounts', schema='email_intel')
    op.drop_table('user_devices', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_token_blacklist_jti'), table_name='refresh_token_blacklist', schema='auth')
    op.drop_table('refresh_token_blacklist', schema='auth')
    op.drop_table('families', schema='auth')
    op.drop_index(op.f('ix_audit_audit_logs_user_id'), table_name='audit_logs', schema='audit')
    op.drop_index(op.f('ix_audit_audit_logs_action'), table_name='audit_logs', schema='audit')
    op.drop_table('audit_logs', schema='audit')
    # ### end Alembic commands ###
